### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by bratva** [IIIristraM/lerna-ts#7]
Need fix xss in [render](https://github.com/IIIristraM/lerna-ts/blob/master/packages/server/src/middlewares/render.tsx#L39) file.

Example https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0

**Comment by IIIristraM** [comment]
fixed by https://github.com/IIIristraM/lerna-ts/pull/14
